### ISSUE TITLE
Port Command Line switch doesn't work

### ISSUE THREAD

**Issue by MeFisto94** [jcarrete5/java-rcon#1]
In https://github.com/jcarrete5/java-rcon/blob/master/src/main/java/net/ddns/jsonet/rcon/RconClient.java#L43, specifying the port via STDIN works, but when the commandLine is present, parsing the string and setting the port value should be part of an else branch parsing the string to an int

**Comment by jcarrete5** [comment]
Not sure what you are suggesting. I just tried to connect my server with the following command and had no issues:
`$ ./java-rcon -p 25575 -H ******* -P *******`

Is something not working for you or are you just suggesting a code change?

**Comment by jcarrete5** [comment]
Ahh, never mind I see what you mean. You submitted a pull request but it was on your fork not on this repository so I didn't see your change.

**Comment by MeFisto94** [comment]
Yeah, sorry, I didn't pay enough attention.
Do note that you need a different port for the issue to manifest
